spring:
  thymeleaf:
    cache: false
  datasource:
    username: batis
    password: 1234
    url: jdbc:oracle:thin:@localhost:1521:credit
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 500
      minimum-idle: 1
      idle-timeout: 60
    schema: classpath:batis-schema.sql
    data: classpath:batis-data.sql
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle8iDialect
  data:
    rest:
      base-path: /api
      default-page-size: 10

mybatis:
  type-aliases-package: com.jony.boot5.boottest.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 9090
  servlet:
    context-path: /
logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG

taco:
  orders:
    rowNum: 20
    pageSize: 20

custom:
  csrf:
    excludeUrls: /rest,/api
---
spring:
  profiles: prod
server:
  port: 8080
taco:
  orders:
    pageSize: 10